### ISSUE TITLE
User Auth MVP Sign Off

### ISSUE THREAD

**Issue by elsonli** [elsonli/a-lull-in-the-museum#2]
# User Auth

## Functionality
- [x] The main button with logo should link to `/`
- [x] Has a working demo login
- [x] Smooth, bug free navigation

### Before Login
- [x] The NavBar has a demo login button
- [x] The `/signup` and `/login` modals also have a demo login button on the form
- [x] Going to a random route `/#/owejkhkjebv` should redirect or display a 404 page
- [x] Errors should display for the `/signup` and `/login` modals
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Cannot sign up with the same username
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login
- [x] Should not be able to visit the `/login` or `/signup` modals
- [x] Should be able to refresh the page and still be logged in

## Style
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Great job so far, Elson! The functionality all looks good to me.  All of my feedback is around styling.  In general, I think we should use Deviant Art as a guide for styling on the session form.  See the photo below.  To go along with your theme, maybe invert the colors so it's black but use spacing, font, size, etc of the form as your blueprint.
![Screen Shot 2020-01-09 at 4 38 55 PM](https://user-images.githubusercontent.com/39272166/72116303-c5cf4a80-32fe-11ea-8dca-2d92728aad46.png)

#### Specific things to really focus on:

### Session Forms
- [ ] width of inputs
- [ ] heigh of inputs
- [ ] use of placeholders
- [ ] clean font throughout (errors are currently still Times)
- [ ] height of form (too squished)
- [ ] space between nav bar and form (should be greater)
- [ ] remove borders from buttons
- [ ] use all caps on button texts

### Splash page
- [ ] get images to render (host on aws or use asset pipeline in the interim)
- [ ] have main image on the splash page extend behind the navbar

### NavBar
- [ ] remove borders around buttons
- [ ] Use all caps to match teamlabs
- [ ] reduce font size of logo a little

**Comment by jenkennedy** [comment]
Looks awesome, Elson!
