### ISSUE TITLE
Artwork MVP Sign Off

### ISSUE THREAD

**Issue by elsonli** [elsonli/a-lull-in-the-museum#3]
# Artworks

### Functionality
- [x] Clicking on an artwork image or title should open the artwork's show page in a new tab
- [x] Hovering over an image shows a play button that zooms in on hover
- [x] Clicking the play button opens a modal with an embedded video
- [x] Previews with no associated videos do not have a play button
- [x] Smooth, bug free navigation

### Style
- [x] All artworks images should darken, zoom, and blur on hover
- [x] All artwork titles should darken and not undo image transition on hover

## Show Page
- [x] Descriptions stored in the database containing the new line character should space it as such
- [x] Clicking on an image should open a modal of an enlarged version of that image
- [x] Going to a random route`/#/artworks/42wajrlk` should redirect or display a 404 page
- [x] Going from one show page to another valid show page should update the page's information
- [x] Show pages have left and right arrows that redirect to the previous or next page (invalid show pages redirect to the index page)

### Before Login
- [x] The `/artworks/:id` page should not display a form to create a comment

### After Login
- [x] The `/artworks/:id` page should display a form to create a comment

## Style
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Looks awesome! Just a couple things to update, as discussed. 

- [ ] Image modal -> remove the border around the image that isn't clickable to close the modal
- [ ] For `/artworks` -> remove grey border around images
