### ISSUE TITLE
Comment MVP Sign Off

### ISSUE THREAD

**Issue by elsonli** [elsonli/a-lull-in-the-museum#5]
# Comments

## Show Page
- [x] All users can view the comments on the artworks

### Before Login
- [x] The `/artworks/:id` page should not contain a comment form to fill out
- [x] Buttons to edit and delete comments should not appear on any of the comments

### After Login
- [x] The `/artworks/:id` page should contain a comment form to fill out
- [x] Leaving a comment on an artwork updates the page (comment is appended to the end of the list, and the comment count is updated)
- [x] Deleting a comment on an artwork updates the page (comment is removed from the list, and the comment count is updated)
- [x] Editing a comment does not change the position of the comment in the list and updates the correct comment
- [x] Buttons to edit and delete comments only appear for the comments written by the current user

## Style
- [x] All relevant elements should have `cursor: pointer` and change color on hover
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
- [ ] Add comments button near the top to scroll down on the page to the comments.  Currently, recruiters might not realize that there is a comments feature

**Comment by jenkennedy** [comment]
- [ ] In the comments component, add a button that redirects to sign in form if the user isn't signed in.  The button could say "Add a comment" or something and then just open up the session modal.  People might not realize that they are able to comment if they don't sign in and poke around.
