### ISSUE TITLE
Dashboard MVP Sign Off

### ISSUE THREAD

**Issue by elsonli** [elsonli/a-lull-in-the-museum#6]
# User Auth
## Functionality
- [x] Should show all of the artworks liked by the user
- [x] Smooth, bug free navigation

### Before Login
- [x] Going to a random route `/#/users/owejkhkjebv` should redirect or display a 404 page
- [x] Going to a valid route `/#/users/1` but not being logged in as that user should redirect or display a 404 page

### After Login
- [x] Should not be able to visit the `/login` or `/signup` modals
- [x] Should be able to refresh the page and still be logged in
- [x] Clicking on an artwork image or title should open the artwork's show page in a new tab
- [x] Hovering over an image shows a play button that zooms in on hover
- [x] Clicking the play button opens a modal with an embedded video
- [x] Previews with no associated videos do not have a play button

## Style
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] All artworks images should darken on hover
- [x] All artwork titles should darken and not undo image transition on hover
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
Looks great!
